### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/fullname#11]
The code is quite messy right now. Would be nice to use [`mem`](https://github.com/sindresorhus/mem) on the exported function instead of assigning to the global `fullname` in every step. Also separate each check into a top level function, so we can easily mix and match checks for each platform, and maybe even do some checks in parallel using `Promise.race()`. I don't have time to do this right now, but could be an interesting exercise for anyone looking to contribute. PR welcome :)

**Comment by canastro** [comment]
I am picking up this issue. 

I implemented some checks using `Promise.race()` as suggested, but I found that this is probably not suited to this module use case, because:

```
The Promise.race(iterable) method returns a promise that resolves or rejects as 
soon as one of the promises in the iterable resolves or rejects, with the value 
or reason from that promise.
```

Check the following jsbin: https://jsbin.com/juqowidoda/1/edit?js,console

Should we keep a approach of sequential calls or do you have any tips regarding this?

**Comment by sindresorhus** [comment]
@canastro You can use this instead: https://github.com/sindresorhus/p-any

**Comment by canastro** [comment]
Just submitted the pull request right before reading this comment, I'll check that out and update the Pull request with p-any.

Thanks @sindresorhus

**Comment by canastro** [comment]
@sindresorhus PR updated here: https://github.com/sindresorhus/fullname/pull/12
